#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,16.9,0
#
I2C_port_for_bq27441.xem3: package/cfg/I2C_port_for_bq27441.xem3.mak

clean::
	-$(RM) package/cfg/I2C_port_for_bq27441.xem3.mak
